name: retech
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.14.3
  

flutter_native_splash:
  color: "#039903"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#039903"
  adaptive_icon_foreground: "assets/icon_sem_fundo.png"   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Removi a linha duplicada de dev_dependencies aqui

flutter:
  uses-material-design: true